config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: "public/sessions"
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

  scope module: :public do
    root to: "homes#top"
    get "homes/about" => "homes#about", as: "about"
    resources :users, except: [:new, :edit, :create, :index, :show, :destroy, :update] do
      collection do
        get "my_page"
        get "unsubscribe"
        get "park_favorites"
        get "sento_favorites"
        patch "update"
        patch "withdraw"
      end
      member do
        get "posts"
      end
    end
    resources :park_favorites, only: [:create, :destroy]
    resources :sento_favorites, only: [:create, :destroy]
    get "users//information/edit" => "users#edit", as: "edit_information_user"
    resources :sentos, only: [:index, :show] do
      resources :sento_reviews, only: [:create]
      member do
        get "reviews"
      end
      collection do
        get "sento_tags"
      end
    end
    resources :parks, only: [:index, :show] do
      resources :park_reviews, only: [:create]
      member do
        get "reviews"
      end
      collection do
        get "park_tags"
      end
    end
    resources :posts, only: [:create, :index, :edit, :update, :destroy] do
      resource :likes, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    get "search" => "searches#search", as: "search"
  end

  namespace :admin do
    resources :users, only: [:show, :index, :edit, :update] do
      member do
        get "posts"
      end
    end
    resources :posts, only: [:index, :show, :destroy] do
      resources :post_comments, only: [:destroy]
    end
    resources :sentos, only: [:new, :create, :index, :show, :edit, :update]
    resources :parks, only: [:new, :create, :index, :show, :edit, :update]
    resources :sento_tags, only: [:index, :create, :edit, :update]
    resources :park_tags, only: [:index, :create, :edit, :update]
    resources :post_tags, only: [:index, :create, :edit, :update]
    resources :park_reviews, only: [:index, :destroy]
    resources :sento_reviews, only: [:index, :destroy]
  end
end




# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/sento.rb
class Sento < ApplicationRecord
  has_many :park_sentos, dependent: :destroy
  has_many :parks, through: :park_sentos
  has_many :sento_favorites, dependent: :destroy
  has_many :users, through: :sento_favorites
  has_many :sento_sento_tags, dependent: :destroy
  has_many :sento_tags, through: :sento_sento_tags
  has_many :sento_reviews, dependent: :destroy

  enum prefecture_id: {
     "エリアを選択": 0,
     大阪: 1, 京都: 2
   }

  validate :check_prefecture_id
  validates :sento_images, presence: { message: "を選択してください" }
  validates :name, presence: true
  validates :prefecture_id, presence: true
  validates :introduction, presence: true
  validates :address, presence: true
  VALID_POSTAL_CODE_REGEX = /\A\d{3}[-]\d{4}\z/
  validates :postal_code, presence: true, format: { with: VALID_POSTAL_CODE_REGEX }
  validates :business_hour, presence: true
  validates :holiday, presence: true
  validates :telephone_number, presence: true
  validates :price, presence: true
  validates :parking, presence: true
  validates :temperature, presence: true
  validates :towel, presence: true
  validates :soap, presence: true
  validates :sento_tag_ids, presence: { message: "を選択してください" }

  scope :active, -> { where(is_active: true) }

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  has_many_attached :sento_images

  def get_first_sento_image
    (sento_images.attached?) ? sento_images.first : "default-image.jpg"
  end

  def active_status
    if is_active == true
      "掲載中"
    else
      "掲載停止中"
    end
  end

  def sauna_status
    if sauna == true
      "あり"
    else
      "なし"
    end
  end

  def open_air_bath_status
    if open_air_bath == true
      "あり"
    else
      "なし"
    end
  end

  def cold_bath_status
    if cold_bath == true
      "あり"
    else
      "なし"
    end
  end

  def self.search_for(word)
    Sento.where("name LIKE ?", "%" + word + "%")
  end
  # def self.seach_for(sento_tag)
  #   Sento.where(sento_tg_id: sento_tag.id)
  # end
  def sento_favorited_by?(user)
    sento_favorites.exists?(user_id: user.id)
  end

  def check_prefecture_id
    if prefecture_id == "エリアを選択"
      errors.add(:prefecture_id, "を選択して下さい")
    end
  end
end

app/controllers/admin/sentos_controller.rb
class Admin::SentosController < ApplicationController
  before_action :authenticate_admin!

  def new
    @sento = Sento.new
  end

  def create
    @sento = Sento.new(sento_params)
    if @sento.save
      redirect_to admin_sento_path(@sento), notice: "銭湯が新規登録されました"
    else
      render :new
    end
  end

  def index
    @sentos = Sento.page(params[:page]).per(10).order(created_at: :desc)
  end

  def show
    @sento = Sento.find(params[:id])
  end

  def edit
    @sento = Sento.find(params[:id])
  end

  def update
    @sento = Sento.find(params[:id])
    if @sento.update(sento_params)
      redirect_to admin_sento_path(@sento), notice: "変更しました"
    else
      render :edit
    end
  end

    private
      def sento_params
        params.require(:sento).permit(:prefecture_id, :name, :introduction, :address, :postal_code, :telephone_number, :business_hour, :holiday, :price, :parking, :sauna, :temperature, :towel, :soap, :open_air_bath, :cold_bath, :is_active, :park_ids, sento_tag_ids: [], sento_images: [])
      end
end

app/helpers/admin/sentos_helper.rb
module Admin::SentosHelper
end

app/views/admin/sentos/_form.html.erb
<table class="table table-borderless">
           <tbody>
              <tr>
                  <div class="form_group">
                    <td>エリアを選択</td>
                    <td><%= f.select :prefecture_id, Sento.prefecture_ids.keys, {} %></td>
                  </div>
              </tr>
              <tr>
                  <div class="form_group">
                    <td>画像</td>
                    <td><%= f.file_field :sento_images, multiple: true %></td>
                  </div>
              </tr>
              <tr>
                  <div class="form_group">
                    <td>銭湯名</td>
                    <td><%= f.text_field :name %></td>
                  </div>
              </tr>
              <tr>
                  <div class="form_group">
                    <td>紹介</td>
                    <td><%= f.text_area :introduction %></td>
                  </div>
              </tr>
              <tr>
                  <div class="form_group">
                    <td>住所</td>
                    <td><%= f.text_field :address %></td>
                  </div>
              </tr>
              <tr>
                  <div class="form_group">
                    <td>郵便番号</td>
                    <td>〒<%= f.text_field :postal_code %></td>
                  </div>
              </tr>
              <tr>
                  <div class="form_group">
                    <td>営業時間</td>
                    <td><%= f.text_field :business_hour %></td>
                  </div>
              </tr>
              <tr>
                  <div class="form_group">
                    <td>定休日</td>
                    <td><%= f.text_field :holiday %></td>
                  </div>
              </tr>
              <tr>
                  <div class="form_group">
                    <td>TEL</td>
                    <td><%= f.text_field :telephone_number %></td>
                  </div>
              </tr>
              <tr>
                  <div class="form_group">
                    <td>料金</td>
                    <td>￥<%= f.text_field :price, placeholder: '大人:490円、子供:390円、サウナ:100円' %></td>
                  </div>
              </tr>
              <tr>
                  <div class="form_group">
                    <td>無料パーキング</td>
                    <td><%= f.text_field :parking %></td>
                  </div>
              </tr>
          </tbody>
        </table>
  <h3>設備情報</h3>
        <table class="table table-borderless">
          <tbody>
              <tr>
                  <div class="form_group">
                    <td>サウナ</td>
                    <td><%= f.radio_button :sauna, true %>
                        <%= f.label :sauna, "あり" %>
                        <%= f.radio_button :sauna, false %>
                        <%= f.label :sauna, "なし" %></td>
                  </div>
              </tr>
              <tr>
                  <div class="form_group">
                    <td>サウナの温度</td>
                    <td>約<%= f.text_field :temperature %>℃</td>
                  </div>
              </tr>
              <tr>
                  <div class="form_group">
                    <td>貸しタオル</td>
                    <td><%= f.text_field :towel %></td>
                  </div>
              </tr>
              <tr>
                  <div class="form_group">
                    <td>石鹸類</td>
                    <td><%= f.text_field :soap %></td>
                  </div>
              </tr>
              <tr>
                  <div class="form_group">
                    <td>露天風呂</td>
                    <td><%= f.radio_button :open_air_bath, true %>
                        <%= f.label :open_air_bath, "あり" %>
                        <%= f.radio_button :open_air_bath, false %>
                        <%= f.label :open_air_bath, "なし" %></td>
                  </div>
              </tr>
              <tr>
                  <div class="form_group">
                    <td>水風呂</td>
                    <td><%= f.radio_button :cold_bath, true %>
                        <%= f.label :cold_bath, "あり" %>
                        <%= f.radio_button :cold_bath, false %>
                        <%= f.label :cold_bath, "なし" %></td>
                  </div>
              </tr>
              <tr>
                  <div class="form_group">
                    <td>掲載ステータス</td>
                    <td><%= f.radio_button :is_active, true %>
                        <%= f.label :is_active, "掲載中" %>
                        <%= f.radio_button :is_active, false %>
                        <%= f.label :is_active, "掲載停止中" %></td>
                  </div>
              </tr>
              <tr>
                  <div class="form_group">
                    <td>タグを選択</td>
                    <td><%= f.collection_check_boxes :sento_tag_ids, SentoTag.all, :ids, :name %></td>
                  </div>
              </tr>
        </tbody>
      </table>

app/views/admin/sentos/edit.html.erb
<%= link_to  admin_sento_path(@sento), class: "back-link-park-sento" do %>
  <i class="fas fa-angle-double-left"></i>BACK
<% end %><br>
<h2 class="admin-title mt-5">銭湯編集</h2>
  <div class="admin-park-sento-new col-12 mt-3 mb-5">
    <%= form_with model: @sento, url: admin_sento_path, method: :patch do |f| %>
      <%= render 'layouts/errors', obj: @sento %>
        <table class="table table-borderless">
          <h3 class="admin-subtitle">基本情報</h3>
           <tbody>
            <tr align="center">
              <div class="form_group">
                <td>掲載ステータス</td>
                <td><%= f.radio_button :is_active, true %>
                    <%= f.label :is_active, "掲載中" %>
                    <%= f.radio_button :is_active, false %>
                    <%= f.label :is_active, "掲載停止中" %>
                </td>
              </div>
            </tr>
            <tr align="center">
              <div class="form_group">
                <td>エリアを選択</td>
                <td><%= f.select :prefecture_id, Sento.prefecture_ids.keys, {}, class: 'form-control col-6' %></td>
              </div>
            </tr>
            <tr align="center">
              <div class="form_group">
                <td>画像</td>
                <td>
                  <% if @sento.sento_images.present? %>
                    <% @sento.sento_images.each do |image| %>
                      <%= image_tag image, size: '200x200' %>
                    <% end %>
                  <% end %>
                  <%= f.file_field :sento_images, multiple: true %>
                </td>
              </div>
            </tr>
            <tr>
                <div class="form_group">
                  <td>銭湯名</td>
                  <td><%= f.text_field :name, class: 'form-control' %></td>
                </div>
            </tr>
            <tr>
                <div class="form_group">
                  <td>紹介</td>
                  <td><%= f.text_area :introduction, class: 'form-control' %></td>
                </div>
            </tr>
            <tr>
                <div class="form_group">
                  <td>住所</td>
                  <td><%= f.text_field :address, class: 'form-control' %></td>
                </div>
            </tr>
            <tr>
                <div class="form_group">
                  <td>郵便番号</td>
                  <td>〒<%= f.text_field :postal_code, placeholder: 'ハイフン含める', class: 'form-control' %></td>
                </div>
            </tr>
            <tr>
                <div class="form_group">
                  <td>営業時間</td>
                  <td><%= f.text_field :business_hour, class: 'form-control' %></td>
                </div>
            </tr>
            <tr>
                <div class="form_group">
                  <td>定休日</td>
                  <td><%= f.text_field :holiday, class: 'form-control' %></td>
                </div>
            </tr>
            <tr>
                <div class="form_group">
                  <td>TEL</td>
                  <td><%= f.text_field :telephone_number, class: 'form-control' %></td>
                </div>
            </tr>
            <tr>
                <div class="form_group">
                  <td>料金</td>
                  <td><%= f.text_field :price, placeholder: '大人:490円、子供:390円、サウナ:100円', class: 'form-control' %></td>
                </div>
            </tr>
            <tr>
                <div class="form_group">
                  <td>無料パーキング</td>
                  <td><%= f.text_field :parking, class: 'form-control' %></td>
                </div>
            </tr>
          </tbody>
        </table>
      <h3 class="admin-subtitle">設備情報</h3>
        <table class="table table-borderless">
          <tbody>
            <tr>
                <div class="form_group">
                  <td>サウナ</td>
                  <td><%= f.radio_button :sauna, true %>
                      <%= f.label :sauna, "あり" %>
                      <%= f.radio_button :sauna, false %>
                      <%= f.label :sauna, "なし" %></td>
                </div>
            </tr>
            <tr>
                <div class="form_group">
                  <td>サウナの温度</td>
                  <td>約<%= f.text_field :temperature, placeholder: 'サウナがない場合は0と記入', class: 'form-control' %>℃</td>
                </div>
            </tr>
            <tr>
                <div class="form_group">
                  <td>貸しタオル</td>
                  <td><%= f.text_field :towel, class: 'form-control' %></td>
                </div>
            </tr>
            <tr>
                <div class="form_group">
                  <td>石鹸類</td>
                  <td><%= f.text_field :soap, class: 'form-control' %></td>
                </div>
            </tr>
            <tr>
                <div class="form_group">
                  <td>露天風呂</td>
                  <td><%= f.radio_button :open_air_bath, true %>
                      <%= f.label :open_air_bath, "あり" %>
                      <%= f.radio_button :open_air_bath, false %>
                      <%= f.label :open_air_bath, "なし" %></td>
                </div>
            </tr>
            <tr>
                <div class="form_group">
                  <td>水風呂</td>
                  <td><%= f.radio_button :cold_bath, true %>
                      <%= f.label :cold_bath, "あり" %>
                      <%= f.radio_button :cold_bath, false %>
                      <%= f.label :cold_bath, "なし" %></td>
                </div>
            </tr>
            <tr>
          </tbody>
        </table>
      <h3 class="admin-subtitle">タグ選択</h3>
        <table class="table table-borderless">
        <tbody>
              <tr align="center">
                <div class="form_group">
                  <td><%= f.collection_check_boxes :sento_tag_ids, SentoTag.all, :id, :name %></td>
                </div>
              </tr>
        </tbody>
      </table>
      <h3 class="admin-subtitle">最寄り銭湯</h3>
                <div class="form_group">
                  <%= f.collection_select :park_ids, Park.all, :id, :name, options = { include_blank: true }, prompt: '選択してください', class: "form-control col-6" %>
                </div>
                <div class="admin-park-sento-submit">
                  <%= f.submit "変更する", class: 'col-5 btn btn-primary mt-3' %>
                </div>
    <% end %>
  </div>

app/views/admin/sentos/index.html.erb
<h3 class="admin-title mt-5">銭湯 LIST</h3>
  <h4><%= link_to "銭湯新規登録", new_admin_sento_path, class: 'btn btn-lg btn-info mb-3' %></h4>
  <h5>全<%= @sentos.total_count %>件</h5>
    <table class="table table-bordered table-striped">
      <thead>
        <tr align="center">
          <th>ID</th>
          <th>銭湯名</th>
          <th>エリア</th>
          <th>お気に入り数</th>
          <th>レビュー数</th>
          <th>レビューの評価(1~5)</th>
          <th>ステータス</th>
          <th>作成日</th>
        </tr>
      </thead>
      <tbody>
        <% @sentos.each do |sento| %>
           <tr align="center">
            <td><%= sento.id %></td>
            <td><%= link_to admin_sento_path(sento.id), class: "admin-obj-name-link" do %><%= sento.name %><% end %></td>
            <td><%= sento.prefecture_id %></td>
            <td><%= sento.sento_favorites.count %>件</td>
            <td><%= sento.sento_reviews.count %>件</td>
            <td><%= sento.sento_reviews.average(:star).to_f.round(1) %></td>
            <td><%= sento.active_status %></td>
            <td><%= l sento.created_at, format: :short %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
<div class="page">
  <%= paginate @sentos %>
</div>

app/views/admin/sentos/new.html.erb
<%= link_to  admin_sentos_path, class: "back-link-park-sento" do %>
  <i class="fas fa-angle-double-left"></i>BACK
<% end %><br>
<h2 class="admin-title mt-5">銭湯新規登録</h2>
  <div class="admin-park-sento-new mt-3 mb-5">
    <%= form_with model: @sento, url: admin_sentos_path, method: :post do |f| %>
      <%= render 'layouts/errors', obj: @sento %>
        <table class="table table-borderless">
          <h3 class="admin-subtitle">基本情報</h3>
           <tbody>
             <tr align="center">
                <div class="form_group">
                  <td>掲載ステータス</td>
                  <td><%= f.radio_button :is_active, true %>
                      <%= f.label :is_active, "掲載中" %>
                      <%= f.radio_button :is_active, false %>
                      <%= f.label :is_active, "掲載停止中" %></td>
                </div>
              </tr>
              <tr align="center">
                <div class="form_group">
                  <td>エリアを選択</td>
                  <td><%= f.select :prefecture_id, Sento.prefecture_ids.keys, {}, class: 'form-control' %></td>
                </div>
              </tr>
              <tr align="center">
                <div class="form_group">
                  <td>画像</td>
                  <td><%= f.file_field :sento_images, multiple: true %></td>
                </div>
              </tr>
              <tr align="center">
                <div class="form_group">
                  <td>銭湯名</td>
                  <td><%= f.text_field :name, placeholder: 'XXX温泉', class: 'form-control' %></td>
                </div>
              </tr>
              <tr align="center">
                <div class="form_group">
                  <td>紹介</td>
                  <td><%= f.text_area :introduction, placeholder: '一言コメント', class: 'form-control' %></td>
                </div>
              </tr>
              <tr align="center">
                <div class="form_group">
                  <td>住所</td>
                  <td><%= f.text_field :address, placeholder: '大阪府XXX',class: 'form-control' %></td>
                </div>
              </tr>
              <tr align="center">
                <div class="form_group">
                  <td>郵便番号</td>
                  <td>〒<%= f.text_field :postal_code, placeholder: '〒ハイフン含める', class: 'form-control' %></td>
                </div>
              </tr>
              <tr align="center">
                <div class="form_group">
                  <td>営業時間</td>
                  <td><%= f.text_field :business_hour, placeholder: '00:00-23:00', class: 'form-control' %></td>
                </div>
              </tr>
              <tr align="center">
                <div class="form_group">
                  <td>定休日</td>
                  <td><%= f.text_field :holiday, placeholder: 'X曜日', class: 'form-control' %></td>
                </div>
              </tr>
              <tr align="center">
                <div class="form_group">
                  <td>TEL</td>
                  <td><%= f.text_field :telephone_number, placeholder: '090-XXXX-XXXX', class: 'form-control' %></td>
                </div>
              </tr>
              <tr align="center">
                <div class="form_group">
                  <td>料金</td>
                  <td><%= f.text_field :price, placeholder: '大人:490円、子供:390円、サウナ:100円', class: 'form-control' %></td>
                </div>
              </tr>
              <tr align="center">
                <div class="form_group">
                  <td>無料パーキング</td>
                  <td><%= f.text_field :parking, placeholder: 'X台無料', class: 'form-control' %></td>
                </div>
              </tr>
          </tbody>
        </table>
<h3 class="admin-subtitle">設備情報</h3>
        <table class="table table-borderless">
          <tbody>
              <tr align="center">
                <div class="form_group">
                  <td>サウナ</td>
                  <td><%= f.radio_button :sauna, true %>
                      <%= f.label :sauna, "あり" %>
                      <%= f.radio_button :sauna, false %>
                      <%= f.label :sauna, "なし" %></td>
                </div>
              </tr>
              <tr align="center">
                <div class="form_group">
                  <td>サウナの温度</td>
                  <td>約<%= f.text_field :temperature, placeholder: 'サウナがない場合は0と記入', class: 'form-control' %>℃</td>
                </div>
              </tr>
              <tr align="center">
                <div class="form_group">
                  <td>貸しタオル</td>
                  <td><%= f.text_field :towel, placeholder: 'あり(有料)', class: 'form-control' %></td>
                </div>
              </tr>
              <tr align="center">
                <div class="form_group">
                  <td>石鹸類</td>
                  <td><%= f.text_field :soap, class: 'form-control' %></td>
                </div>
              </tr>
              <tr align="center">
                <div class="form_group">
                  <td>露天風呂</td>
                  <td><%= f.radio_button :open_air_bath, true %>
                      <%= f.label :open_air_bath, "あり" %>
                      <%= f.radio_button :open_air_bath, false %>
                      <%= f.label :open_air_bath, "なし" %></td>
                </div>
              </tr>
              <tr align="center">
                <div class="form_group">
                  <td>水風呂</td>
                  <td><%= f.radio_button :cold_bath, true %>
                      <%= f.label :cold_bath, "あり" %>
                      <%= f.radio_button :cold_bath, false %>
                      <%= f.label :cold_bath, "なし" %></td>
                </div>
              </tr>
         </tbody>
      </table>
<h3 class="admin-subtitle">タグ選択</h3>
      <table class="table table-borderless">
        <tbody>
              <tr align="center">
                <div class="form_group">
                  <td><%= f.collection_check_boxes :sento_tag_ids, SentoTag.all, :id, :name %></td>
                </div>
              </tr>
        </tbody>
      </table>
      <div class="admin-park-sento-submit">
        <%= f.submit "新規登録", class: 'col-5 btn btn-primary mt-3' %>
      </div>
    <% end %>
  </div>

app/views/admin/sentos/show.html.erb
<%= link_to  admin_sentos_path, class: "back-link-park-sento" do %>
  <i class="fas fa-angle-double-left"></i>銭湯LIST
<% end %><br>
<h2 class="admin-title mt-5">
  銭湯詳細
</h2>
<div class="park-sento-title-row">
    <h2 class="park-sento-name"><%= @sento.name %></h2>
</div>
<div class="park-sento-image-index">
  <h3 class="admin-near-link mt-5">
    <%= link_to "最寄りパークを追加、詳細を編集する", edit_admin_sento_path(@sento), class: "btn btn-lg btn-warning" %>
  </h3>
  <% @sento.sento_images.each do |sento_image| %>
      <%= image_tag sento_image, size: '700x450', class: "park_sento_image" %><br>
  <% end %>
  <div class="park-sento-intro">
    <%= @sento.introduction %>
  </div>
  <div class="park-sento-tag-list">
    <i class="fas fa-tag" style="color: #628961;"></i>
    <% @sento.sento_tags.each do |sento_tag| %>
       #<%= sento_tag.name %>
    <% end %>
  </div>
</div>
<h3 class="info-title">基本情報</h3>
<div class="park-sento-info">
  <table class="table table-borderless">
    <tbody>
      <tr>
          <td>掲載ステータス</td>
          <td><%= @sento.active_status %></td>
      </tr>
      <tr>
          <td>エリア</td>
          <td><%= @sento.prefecture_id %></td>
      </tr>
      <tr>
          <td>住所</td>
          <td><%= @sento.address %></td>
      </tr>
      <tr>
          <td>郵便番号</td>
          <td>〒<%= @sento.postal_code %></td>
      </tr>
      <tr>
          <td>オープン時間</td>
          <td><%= @sento.business_hour %></td>
      </tr>
      <tr>
          <td>定休日</td>
          <td><%= @sento.holiday %></td>
      </tr>
      <tr>
          <td>TEL</td>
          <td><%= @sento.telephone_number %></td>
      </tr>
      <tr>
          <td>料金</td>
          <td><%= @sento.price %></td>
      </tr>
      <tr>
          <td>無料パーキング</td>
          <td><%= @sento.parking %></td>
      </tr>
    </tbody>
  </table>
</div>
<h3 class="info-title">設備情報</h3>
<div class="park-sento-info">
  <table class="table table-borderless">
    <tbody>
      <tr>
        <td>サウナ</td>
        <td><%= @sento.sauna_status %>
      </tr>
      <tr>
        <td>サウナの温度</td>
        <td>
          <% if @sento.temperature == 0 %>
              サウナはありません
          <% else %>
              約<%= @sento.temperature %>℃
          <% end %>
        </td>
      </tr>
      <tr>
        <td>貸しタオル</td>
        <td><%= @sento.towel %></td>
      </tr>
      <tr>
        <td>石鹸類</td>
        <td><%= @sento.soap %></td>
      </tr>
      <tr>
        <td>露天風呂</td>
        <td><%= @sento.open_air_bath_status %></td>
      </tr>
      <tr>
        <td>水風呂</td>
        <td><%= @sento.cold_bath_status %></td>
      </tr>
    </tbody>
  </table>
</div>
<div class="near-name">
  <h3 class="info-title">最寄りパーク</h3><br>
  <% if @sento.parks.present? %>
      <% @sento.parks.each do |park| %>
          <%= link_to admin_park_path(park.id), class: 'near' do %>
            <%= park.name %>
          <% end %>
      <% end %>
  <% else %>
    <h5>まだ情報はありません</h5>
  <% end %>
</div>
<h3 class="admin-near-link">
  <%= link_to "最寄りパークを追加、詳細を編集する", edit_admin_sento_path(@sento), class: "btn btn-lg btn-warning" %>
</h3>