config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: "public/sessions"
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

  scope module: :public do
    root to: "homes#top"
    get "homes/about" => "homes#about", as: "about"
    resources :users, except: [:new, :edit, :create, :index, :show, :destroy, :update] do
      collection do
        get "my_page"
        get "unsubscribe"
        get "park_favorites"
        get "sento_favorites"
        patch "update"
        patch "withdraw"
      end
      member do
        get "posts"
      end
    end
    resources :park_favorites, only: [:create, :destroy]
    resources :sento_favorites, only: [:create, :destroy]
    get "users//information/edit" => "users#edit", as: "edit_information_user"
    resources :sentos, only: [:index, :show] do
      resources :sento_reviews, only: [:create]
      member do
        get "reviews"
      end
      collection do
        get "sento_tags"
      end
    end
    resources :parks, only: [:index, :show] do
      resources :park_reviews, only: [:create]
      member do
        get "reviews"
      end
      collection do
        get "park_tags"
      end
    end
    resources :posts, only: [:create, :index, :edit, :update, :destroy] do
      resource :likes, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    get "search" => "searches#search", as: "search"
  end

  namespace :admin do
    resources :users, only: [:show, :index, :edit, :update] do
      member do
        get "posts"
      end
    end
    resources :posts, only: [:index, :show, :destroy] do
      resources :post_comments, only: [:destroy]
    end
    resources :sentos, only: [:new, :create, :index, :show, :edit, :update]
    resources :parks, only: [:new, :create, :index, :show, :edit, :update]
    resources :sento_tags, only: [:index, :create, :edit, :update]
    resources :park_tags, only: [:index, :create, :edit, :update]
    resources :post_tags, only: [:index, :create, :edit, :update]
    resources :park_reviews, only: [:index, :destroy]
    resources :sento_reviews, only: [:index, :destroy]
  end
end




# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/park.rb
class Park < ApplicationRecord
  has_many :park_sections, dependent: :destroy
  has_many :sections, through: :park_sections
  has_many :park_sentos, dependent: :destroy
  has_many :sentos, through: :park_sentos
  has_many :park_favorites, dependent: :destroy
  has_many :users, through: :park_favorites
  has_many :park_park_tags, dependent: :destroy
  has_many :park_tags, through: :park_park_tags
  has_many :park_reviews, dependent: :destroy

  enum prefecture_id: {
     "エリアを選択": 0,
     大阪: 1, 京都: 2
   }

  validate :check_prefecture_id
  validates :park_images, presence: { message: "を選択してください" }
  validates :name, presence: true
  validates :introduction, presence: true
  validates :address, presence: true
  VALID_POSTAL_CODE_REGEX = /\A\d{3}[-]\d{4}\z/
  validates :postal_code, presence: true, format: { with: VALID_POSTAL_CODE_REGEX }
  validates :business_hour, presence: true
  validates :holiday, presence: true
  validates :telephone_number, presence: true
  validates :price, presence: true
  validates :parking, presence: true
  validates :helmet, presence: true
  validates :park_tag_ids, presence: { message: "を選択してください" }



  scope :star_count, -> { order(star: :desc) }
  scope :active, -> { where(is_active: true) }

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  has_many_attached :park_images

  def active_status
    if is_active == true
      "掲載中"
    else
      "掲載停止中"
    end
  end

  def self.search_for(word)
    Park.where("name LIKE ?", "%" + word + "%")
  end

  def park_favorited_by?(user)
    park_favorites.exists?(user_id: user.id)
  end
  # def self.count_active_park
  #   Park.where(is_active: true).count
  # end

  def check_prefecture_id
    if prefecture_id == "エリアを選択"
      errors.add(:prefecture_id, "を選択して下さい")
    end
  end
end

app/controllers/admin/parks_controller.rb
class Admin::ParksController < ApplicationController
  before_action :authenticate_admin!

  def new
    @park = Park.new
  end

  def create
    @park = Park.new(park_params)
    if @park.save
      redirect_to admin_park_path(@park), notice: "パークが新規登録されました"
    else
      render :new
    end
  end

  def index
    @parks = Park.page(params[:page]).per(10).order(created_at: :desc)
  end

  def show
    @park = Park.find(params[:id])
  end

  def edit
    @park = Park.find(params[:id])
  end

  def update
    @park = Park.find(params[:id])
    if @park.update(park_params)
      redirect_to admin_park_path(@park), notice: "変更しました"
    else
      render :edit
    end
  end

    private
      def park_params
        params.require(:park).permit(:prefecture_id, :name, :introduction, :address, :postal_code, :telephone_number, :business_hour, :holiday, :price, :parking, :helmet, :is_active, :sento_ids, park_tag_ids: [], park_images: [], section_ids: [])
      end
end

app/helpers/admin/parks_helper.rb
module Admin::ParksHelper
end

app/views/admin/parks/edit.html.erb
<%= link_to  admin_park_path(@park), class: "back-link-park-sento" do %>
  <i class="fas fa-angle-double-left"></i>BACK
<% end %><br>
<h2 class="admin-title mt-5">パーク編集</h2>
  <div class="admin-park-sento-new col-12 mt-3 mb-5">
    <%= form_with model: @park, url: admin_park_path, method: :patch do |f| %>
      <%= render 'layouts/errors', obj: @park %>
        <table class="table table-borderless">
          <h3 class="admin-subtitle">基本情報</h3>
           <tbody>
              <tr align="center">
                <div class="form_group">
                  <td>掲載ステータス</td>
                  <td><%= f.radio_button :is_active, true %>
                      <%= f.label :is_active, "掲載中" %>
                      <%= f.radio_button :is_active, false %>
                      <%= f.label :is_active, "掲載停止中" %>
                  </td>
                </div>
              </tr>
              <tr align="center">
                <div class="form_group">
                  <td>エリアを選択</td>
                  <td><%= f.select :prefecture_id, Park.prefecture_ids.keys, {}, class: 'form-control col-6' %></td>
                </div>
              </tr>
              <tr align="center">
                <div class="form_group">
                  <td>画像</td>
                  <td>
                    <% if @park.park_images.present? %>
                      <% @park.park_images.each do |image| %>
                        <%= image_tag image, size: '200x200' %>
                      <% end %>
                    <% end %>
                    <%= f.file_field :park_images, multiple: true %>
                  </td>
                </div>
              </tr>
              <tr>
                  <div class="form_group">
                    <td>パーク名</td>
                    <td><%= f.text_field :name, class: 'form-control' %></td>
                  </div>
              </tr>
              <tr>
                  <div class="form_group">
                    <td>紹介</td>
                    <td><%= f.text_area :introduction, class: 'form-control' %></td>
                  </div>
              </tr>
              <tr>
                  <div class="form_group">
                    <td>住所</td>
                    <td><%= f.text_field :address, class: 'form-control' %></td>
                  </div>
              </tr>
              <tr>
                  <div class="form_group">
                    <td>郵便番号</td>
                    <td>〒<%= f.text_field :postal_code, placeholder: 'ハイフン含める', class: 'form-control' %></td>
                  </div>
              </tr>
              <tr>
                  <div class="form_group">
                    <td>オープン時間</td>
                    <td><%= f.text_field :business_hour, class: 'form-control' %></td>
                  </div>
              </tr>
              <tr>
                  <div class="form_group">
                    <td>定休日</td>
                    <td><%= f.text_field :holiday, class: 'form-control' %></td>
                  </div>
              </tr>
              <tr>
                  <div class="form_group">
                    <td>TEL</td>
                    <td><%= f.text_field :telephone_number, class: 'form-control' %></td>
                  </div>
              </tr>
              <tr>
                  <div class="form_group">
                    <td>料金</td>
                    <td><%= f.text_field :price, placeholder: '大人:490円、子供:390円', class: 'form-control' %></td>
                  </div>
              </tr>
              <tr>
                  <div class="form_group">
                    <td>無料パーキング</td>
                    <td><%= f.text_field :parking, class: 'form-control' %></td>
                  </div>
              </tr>
               <tr>
                  <div class="form_group">
                    <td>ヘルメット義務</td>
                    <td><%= f.text_field :helmet, class: 'form-control' %></td>
                  </div>
              </tr>
          </tbody>
        </table>
      <h3 class="admin-subtitle">セクション</h3>
                  <div class="form-group">
                    <%= f.collection_check_boxes :section_ids, Section.all, :id, :name, class: 'form-control' %>
                  </div>
      <h3 class="admin-subtitle">タグ選択</h3>
                  <div class="form_group">
                    <%= f.collection_check_boxes :park_tag_ids, ParkTag.all, :id, :name, class: 'form-control, pr-3' %>
                  </div>
      <h3 class="admin-subtitle">最寄り銭湯</h3>
                  <div class="form_group">
                    <%= f.collection_select :sento_ids, Sento.all, :id, :name, options = { include_blank: true }, prompt: '選択してください', class: "form-control col-6" %>
                  </div>
                  <div class="admin-park-sento-submit">
                    <%= f.submit "銭湯を追加、変更を保存する", class: 'col-5 btn btn-success mt-3' %>
                  </div>
    <% end %>
  </div>

app/views/admin/parks/index.html.erb
<h3 class="admin-title mt-5">PARK LIST</h3>
  <h4><%= link_to "パーク新規登録", new_admin_park_path, class: 'btn btn-lg btn-info mb-3' %></h4>
  <h5>全<%= @parks.total_count %>件</h5>
    <table class="table table-bordered table-striped">
      <thead>
        <tr align="center">
          <th>ID</th>
          <th>パーク名</th>
          <th>エリア</th>
          <th>お気に入り数</th>
          <th>レビュー数</th>
          <th>レビューの評価(1~5)</th>
          <th>ステータス</th>
          <th>作成日</th>
        </tr>
      </thead>
      <tbody>
        <% @parks.each do |park| %>
          <tr align="center">
            <td><%= park.id %></td>
            <td><%= link_to admin_park_path(park.id), class: "admin-obj-name-link" do %><%= park.name %><% end %></td>
            <td><%= park.prefecture_id %></td>
            <td><%= park.park_favorites.count %>件</td>
            <td><%= park.park_reviews.count %>件</td>
            <td><%= park.park_reviews.average(:star).to_f.round(1) %></td>
            <td><%= park.active_status %></td>
            <td><%= l park.created_at, format: :short %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <div class="page">
    <%= paginate @parks %>
  </div>

app/views/admin/parks/new.html.erb
<%= link_to  admin_parks_path, class: "back-link-park-sento" do %>
  <i class="fas fa-angle-double-left"></i>BACK
<% end %><br>
<h2 class="admin-title mt-5">パーク新規登録</h2>
<div class="admin-park-sento-new col-12 mt-3 mb-5">
    <%= form_with model: @park, url: admin_parks_path, method: :post do |f| %>
      <%= render 'layouts/errors', obj: @park %>
        <table class="table table-borderless">
          <h3 class="admin-subtitle">基本情報</h3>
           <tbody>
              <tr align="center">
                <div class="form_group">
                  <td>掲載ステータス</td>
                  <td><%= f.radio_button :is_active, true %>
                      <%= f.label :is_active, "掲載中" %>
                      <%= f.radio_button :is_active, false %>
                      <%= f.label :is_active, "掲載停止中" %>
                  </td>
                </div>
              </tr>
              <tr align="center">
                <div class="form_group">
                  <td>エリアを選択</td>
                  <td><%= f.select :prefecture_id, Park.prefecture_ids.keys, {}, class: 'form-control col-6' %></td>
                </div>
              </tr>
              <tr align="center">
                <div class="form_group">
                  <td>画像</td>
                  <td><%= f.file_field :park_images, multiple: true %></td>
                </div>
              </tr>
              <tr align="center">
                <div class="form_group">
                  <td>パーク名</td>
                  <td><%= f.text_field :name, placeholder: 'XXXパーク', class: 'form-control' %></td>
                </div>
              </tr>
              <tr align="center">
                <div class="form_group">
                  <td>紹介</td>
                  <td><%= f.text_area :introduction, placeholder: '一言コメント', class: 'form-control' %></td>
                </div>
              </tr>
              <tr align="center">
                <div class="form_group">
                  <td>住所</td>
                  <td><%= f.text_field :address, placeholder: '大阪府XXX',class: 'form-control' %></td>
                </div>
              </tr>
              <tr align="center">
                <div class="form_group">
                  <td>郵便番号</td>
                  <td><%= f.text_field :postal_code, placeholder: '〒ハイフン含める', class: 'form-control' %></td>
                </div>
              </tr>
              <tr align="center">
                <div class="form_group">
                  <td>オープン時間</td>
                  <td><%= f.text_field :business_hour, placeholder: '00:00-23:00', class: 'form-control' %></td>
                </div>
              </tr>
              <tr align="center">
                <div class="form_group">
                  <td>定休日</td>
                  <td><%= f.text_field :holiday, placeholder: 'X曜日', class: 'form-control' %></td>
                </div>
              </tr>
              <tr align="center">
                <div class="form_group">
                  <td>TEL</td>
                  <td><%= f.text_field :telephone_number, placeholder: '090-XXXX-XXXX', class: 'form-control' %></td>
                </div>
              </tr>
              <tr align="center">
                <div class="form_group">
                  <td>料金</td>
                  <td><%= f.text_field :price, placeholder: '大人:XXX円、子供:XXX円', class: 'form-control ' %></td>
                </div>
              </tr>
              <tr align="center">
                <div class="form_group">
                  <td>無料パーキング</td>
                  <td><%= f.text_field :parking, placeholder: 'X台無料', class: 'form-control' %></td>
                </div>
              </tr>
               <tr align="center">
                <div class="form_group">
                  <td>ヘルメット義務</td>
                  <td><%= f.text_field :helmet, placeholder: '小学生のみ', class: 'form-control' %></td>
                </div>
              </tr>
          </tbody>
        </table>
      <h3 class="admin-subtitle">セクション</h3>
                  <div class="form-group">
                    <%= f.collection_check_boxes :section_ids, Section.all, :id, :name, class: 'form-control' %>
                  </div>

      <h3 class="admin-subtitle">タグ選択</h3>
                  <div class="form_group">
                    <%= f.collection_check_boxes :park_tag_ids, ParkTag.all, :id, :name, class: 'form-control, pr-3' %>
                  </div>
                  <div class="admin-park-sento-submit">
                    <%= f.submit "新規登録", class: 'col-5 btn btn-primary mt-3' %>
                  </div>
    <% end %>
</div>

app/views/admin/parks/show.html.erb
<%= link_to  admin_parks_path, class: "back-link-park-sento" do %>
  <i class="fas fa-angle-double-left"></i>PARK LIST
<% end %><br>
<h2 class="admin-title mt-5">
  パーク詳細
</h2>
  <div class="park-sento-title-row">
    <h2 class="park-sento-name"><%= @park.name %></h2>
  </div>
  <div class="park-sento-image-index">
    <h3 class="admin-near-link mt-5">
      <%= link_to "最寄り銭湯を追加、詳細を編集する", edit_admin_park_path(@park), class: "btn btn-lg btn-warning" %>
    </h3>
    <% @park.park_images.each do |park_image| %>
        <%= image_tag park_image, size: '700x450', class: "park_sento_image" %><br>
    <% end %>
    <div class="park-sento-intro">
      <%= @park.introduction %>
    </div>
    <div class="park-sento-tag-list">
      <i class="fas fa-tag" style="color: #628961;"></i>
      <% @park.park_tags.each do |park_tag| %>
        #<%= park_tag.name %>
      <% end %>
    </div>
  </div>
<h3 class="info-title">基本情報</h3>
  <div class="park-sento-info">
    <table class="table table-borderless">
      <tbody>
        <tr>
            <td>掲載ステータス</td>
            <td><%= @park.active_status %></td>
        </tr>
        <tr>
            <td>エリア</td>
            <td><%= @park.prefecture_id %></td>
        </tr>
        <tr>
            <td>住所</td>
            <td><%= @park.address %></td>
        </tr>
        <tr>
            <td>郵便番号</td>
            <td>〒<%= @park.postal_code %></td>
        </tr>
        <tr>
            <td>オープン時間</td>
            <td><%= @park.business_hour %></td>
        </tr>
        <tr>
            <td>定休日</td>
            <td><%= @park.holiday %></td>
        </tr>
        <tr>
            <td>TEL</td>
            <td><%= @park.telephone_number %></td>
        </tr>
        <tr>
            <td>料金</td>
            <td><%= @park.price %></td>
        </tr>
        <tr>
            <td>無料パーキング</td>
            <td><%= @park.parking %></td>
        </tr>
        <tr>
            <td>ヘルメット義務</td>
            <td><%= @park.helmet %></td>
        </tr>
      </tbody>
    </table>
  </div>
<div>
  <h3 class="info-title">セクション</h3><br>
        <% Section.all.each do |section| %>
          <% if @park.sections.include?(section) %>
            ○<%= section.name %><br>
          <% else %>
            x<%= section.name %><br>
          <% end %>
        <% end %>
</di>
<div class="near-name">
    <h3 class="info-title">最寄り銭湯</h3><br>
    <% if @park.sentos.present? %>
        <% @park.sentos.each do |sento| %>
            <%= link_to admin_sento_path(sento.id), class: 'near' do %>
              <%= sento.name %>
            <% end %>
        <% end %>
    <% else %>
      <h5>まだ情報はありません</h5>
    <% end %>
</div>
<h3 class="admin-near-link">
  <%= link_to "最寄り銭湯を追加、詳細を編集する", edit_admin_park_path(@park), class: "btn btn-lg btn-warning" %>
</h3>