config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: "public/sessions"
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

  scope module: :public do
    root to: "homes#top"
    get "homes/about" => "homes#about", as: "about"
    resources :users, except: [:new, :edit, :create, :index, :show, :destroy, :update] do
      collection do
        get "my_page"
        get "unsubscribe"
        get "park_favorites"
        get "sento_favorites"
        patch "update"
        patch "withdraw"
      end
      member do
        get "posts"
      end
    end
    resources :park_favorites, only: [:create, :destroy]
    resources :sento_favorites, only: [:create, :destroy]
    get "users//information/edit" => "users#edit", as: "edit_information_user"
    resources :sentos, only: [:index, :show] do
      resources :sento_reviews, only: [:create]
      member do
        get "reviews"
      end
      collection do
        get "sento_tags"
      end
    end
    resources :parks, only: [:index, :show] do
      resources :park_reviews, only: [:create]
      member do
        get "reviews"
      end
      collection do
        get "park_tags"
      end
    end
    resources :posts, only: [:create, :index, :edit, :update, :destroy] do
      resource :likes, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    get "search" => "searches#search", as: "search"
  end

  namespace :admin do
    resources :users, only: [:show, :index, :edit, :update] do
      member do
        get "posts"
      end
    end
    resources :posts, only: [:index, :show, :destroy] do
      resources :post_comments, only: [:destroy]
    end
    resources :sentos, only: [:new, :create, :index, :show, :edit, :update]
    resources :parks, only: [:new, :create, :index, :show, :edit, :update]
    resources :sento_tags, only: [:index, :create, :edit, :update]
    resources :park_tags, only: [:index, :create, :edit, :update]
    resources :post_tags, only: [:index, :create, :edit, :update]
    resources :park_reviews, only: [:index, :destroy]
    resources :sento_reviews, only: [:index, :destroy]
  end
end




# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :post_post_tags, dependent: :destroy
  has_many :post_tags, through: :post_post_tags

  validates :prefecture_id, presence: { message: "を選択してください" }
  validates :post_park_image, presence: { message: "を選択してください" }
  validates :post_sento_image, presence: { message: "を選択してください" }
  validates :park, presence: true
  validates :sento, presence: true
  validates :park_caption, presence: true
  validates :sento_caption, presence: true

  enum prefecture_id: {
     北海道: 1, 青森県: 2, 岩手県: 3, 宮城県: 4, 秋田県: 5, 山形県: 6, 福島県: 7,
     茨城県: 8, 栃木県: 9, 群馬県: 10, 埼玉県: 11, 千葉県: 12, 東京都: 13, 神奈川県: 14,
     新潟県: 15, 富山県: 16, 石川県: 17, 福井県: 18, 山梨県: 19, 長野県: 20,
     岐阜県: 21, 静岡県: 22, 愛知県: 23, 三重県: 24,
     滋賀県: 25, 京都府: 26, 大阪府: 27, 兵庫県: 28, 奈良県: 29, 和歌山県: 30,
     鳥取県: 31, 島根県: 32, 岡山県: 33, 広島県: 34, 山口県: 35,
     徳島県: 36, 香川県: 37, 愛媛県: 38, 高知県: 39,
     福岡県: 40, 佐賀県: 41, 長崎県: 42, 熊本県: 43, 大分県: 44, 宮崎県: 45, 鹿児島県: 46,
     沖縄県: 47
   }

  has_one_attached :post_park_image
  has_one_attached :post_sento_image

  def get_post_park_image
    (post_park_image.attached?) ? post_park_image : "default-image.jpg"
  end

  def get_post_sento_image
    (post_sento_image.attached?) ? post_sento_image : "default-image.jpg"
  end

  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @posts = Post.page(params[:page]).per(10).order(created_at: :desc)
    @users = User.all
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user_id
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to admin_posts_path, notice: "投稿を削除しました"
  end

    private
      def post_params
        params.require(:post).permit(:user_id, :prefecture_id, :park, :sento, :park_caption, :sento_caption, :post_park_image, :post_sento_image)
      end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/index.html.erb
<h3 class="admin-title mt-5">ユーザー投稿一覧</h3>
<h5>全<%= @posts.total_count %>件</h5>
  <table class="table table-bordered table-striped">
    <thead>
      <tr align="center">
        <td>投稿日</td>
        <td>ユーザー名</td>
        <td>パーク名</td>
        <td>銭湯名</td>
        <td>エリア</td>
        <td>いいね</td>
        <td>コメント</td>
        <td>詳細</td>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr align="center">
          <td><%= l post.created_at, format: :short %></td>
          <td><%= link_to admin_user_path(post.user.id), class: "admin-obj-name-link" do %><%= post.user.name %><% end %></td>
          <td><%= post.park %></td>
          <td><%= post.sento %></td>
          <td><%= post.prefecture_id %></td>
          <td><%= post.likes.count %></td>
          <td><%= post.post_comments.count %></td>
          <td><%= link_to "表示する", admin_post_path(post.id), class: "btn btn-sm btn-info" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<div class="page">
    <%= paginate @posts %>
</div>

app/views/admin/posts/show.html.erb
<h2 class="admin-title"><%= @post.user.name %>の投稿詳細</h2>
<div class="admin-links-btn">
  <%= link_to "会員情報詳細画面へ", admin_user_path(@user), class: 'btn btn btn-success mr-2' %>
  <%= link_to "この会員の投稿一覧へ", posts_admin_user_path(@user), class: 'btn btn btn-info mr-2' %>
  <%= link_to "投稿を削除する", admin_post_path(@post), method: :delete, data: { confirm: '投稿を削除しますか？'}, class: 'btn btn btn-danger'%>
</div>
<div class="user-post-list mb-5">
  <div class="post-area-date-box">
    <div class="post-area-date">
      エリア: <%= @post.prefecture_id %>
    </div>
    <div></div>
    <div class="post-area-date">
      投稿日：<%= l @post.created_at, format: :short %>
    </div>
  </div>
  <div class="row post-box">
    <div class="col-md-5">
      <div class="card mb-2">
        <h4 class="post-park-sento-title">
          PARK
        </h4>
        <%= image_tag @post.get_post_park_image, class: 'card-img-top', height:'350' %>
        <div class="card-body">
          <div class="post-park-sento-explain">
           <i class="fas fa-store-alt"></i>:  <strong><%= @post.park %></strong><br>
           <i class="fas fa-comment"></i>:  <%= @post.park_caption %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-5">
      <div class="card mb-2">
        <h4 class="post-park-sento-title">
          銭湯
        </h4>
        <%= image_tag @post.get_post_sento_image, class: 'card-img-top', height:'350' %>
        <div class="card-body">
          <div class="post-park-sento-explain">
            <i class="fas fa-store-alt"></i>: <strong><%= @post.sento %></strong><br>
            <i class="fas fa-comment"></i>: <%= @post.sento_caption %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="post-tag-list">
    <i class="fas fa-tag" style="color: #628961;"></i>
    <% @post.post_tags.each do |post_tag| %>
      #<%= post_tag.name %>
    <% end %>
  </div>
  <div class="admin-like-comment mb-3">
    いいね：<%= @post.likes.count %>件<br>
    コメント:<%= @post.post_comments.count %>件
  </div>
  <% @post.post_comments.each do |post_comment| %>
    <i class="far fa-user"></i>: <%= link_to "#{post_comment.user.name}", admin_user_path(post_comment.user), class: "admin_comment_user"%><br>
    <div class="comment-list">
      <%= post_comment.comment %>
      <div class="comment-post-time">
        <%= l post_comment.created_at, format: :default %>
        <%= link_to "コメントを削除する", admin_post_post_comment_path(post_comment.post, post_comment), method: :delete, data: { confirm: 'コメントを削除しますか？'}, class: 'btn btn-sm btn-danger mb-2'%>
      </div>
    </div>
  <% end %>
</div>