config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: "public/sessions"
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
  }

  scope module: :public do
    root to: "homes#top"
    get "homes/about" => "homes#about", as: "about"
    resources :users, except: [:new, :edit, :create, :index, :show, :destroy, :update] do
      collection do
        get "my_page"
        get "unsubscribe"
        get "park_favorites"
        get "sento_favorites"
        patch "update"
        patch "withdraw"
      end
      member do
        get "posts"
      end
    end
    resources :park_favorites, only: [:create, :destroy]
    resources :sento_favorites, only: [:create, :destroy]
    get "users//information/edit" => "users#edit", as: "edit_information_user"
    resources :sentos, only: [:index, :show] do
      resources :sento_reviews, only: [:create]
      member do
        get "reviews"
      end
      collection do
        get "sento_tags"
      end
    end
    resources :parks, only: [:index, :show] do
      resources :park_reviews, only: [:create]
      member do
        get "reviews"
      end
      collection do
        get "park_tags"
      end
    end
    resources :posts, only: [:create, :index, :edit, :update, :destroy] do
      resource :likes, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    get "search" => "searches#search", as: "search"
  end

  namespace :admin do
    resources :users, only: [:show, :index, :edit, :update] do
      member do
        get "posts"
      end
    end
    resources :posts, only: [:index, :show, :destroy] do
      resources :post_comments, only: [:destroy]
    end
    resources :sentos, only: [:new, :create, :index, :show, :edit, :update]
    resources :parks, only: [:new, :create, :index, :show, :edit, :update]
    resources :sento_tags, only: [:index, :create, :edit, :update]
    resources :park_tags, only: [:index, :create, :edit, :update]
    resources :post_tags, only: [:index, :create, :edit, :update]
    resources :park_reviews, only: [:index, :destroy]
    resources :sento_reviews, only: [:index, :destroy]
  end
end




# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/views/layouts/_errors.html.erb
<%# byebug %>
<div class="errors-color">
  <% if obj.errors.any? %>
    <div id="error_explanation">
      <h4><%= t("errors.template.header", model: obj.model_name.human, count: obj.errors.count) %></h4>

      <ul>
        <% obj.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% else %>
  <div id="error_explanation"></div>
  <% end %>
</div>

app/views/layouts/_flash.html.erb
<%= flash[:notice_message] %>

app/views/layouts/_header.html.erb
<!--<nav class="navbar navbar-expand-lg navbar-light">-->
<!--    <div class="container-fluid">-->
<div class="header-container">
  <!--<%# if admin_signed_in? %>-->
  <!--  <div class ="main-logo">-->
  <!--    <%#= link_to "SKATE AND SENTO(管理者用)", root_path, class: "main-logo-link" %>-->
  <!--  </div>-->
  <!--<%# else %>-->

  <%# end %>
  <!--        <div class="collapse navbar-collapse justify-content-around">-->
  <!--          <ul class="navbar-nav ml-auto">-->
  <div id="hm-icon">
      <a class="menu-trigger" href="#">
        <span></span>
        <span></span>
        <span></span>
      </a>
  </div>
  <% if request.fullpath.include? "admin" %>
    <div id="sp-menu">
      <% if admin_signed_in? %>
        <ul class="nav-list-position">
          <li><%= link_to "パーク", admin_parks_path, class: 'nav-link' %></li>
          <li><%= link_to "銭湯", admin_sentos_path, class: 'nav-link' %></li>
          <li><%= link_to "パークレビュー", admin_park_reviews_path, class: 'nav-link' %></li>
          <li><%= link_to "銭湯レビュー", admin_sento_reviews_path, class: 'nav-link' %></li>
          <li><%= link_to "ユーザー", admin_users_path, class: 'nav-link' %></li>
          <li><%= link_to "ユーザー投稿", admin_posts_path, class: 'nav-link' %></li>
          <li><%= link_to "パークタグ", admin_park_tags_path, class: 'nav-link' %></li>
          <li><%= link_to "銭湯タグ", admin_sento_tags_path, class: 'nav-link' %></li>
          <li><%= link_to "投稿タグ", admin_post_tags_path, class: 'nav-link' %></li>
          <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, data:{ confirm: 'ログアウトしますか？'}, class: 'nav-link'%></li>
        </ul>
      <% else %>
        <ul class="nav-list-position">
          <li><%= link_to "ログインする", new_admin_session_path, class: 'nav-link' %></li>
        </ul>
      <% end %>
    </div>
  <% else %>
    <div id="sp-menu">
        <% if user_signed_in? %>
          <ul class="nav-list-position">
            <li><%= link_to "SKATEPARK", parks_path, class: 'nav-link' %></li>
            <li><%= link_to "銭湯", sentos_path, class: 'nav-link' %></li>
            <li><%= link_to "お気に入りPARK", park_favorites_users_path, class: 'nav-link' %></li>
            <li><%= link_to "お気に入り銭湯", sento_favorites_users_path, class: 'nav-link' %></li>
            <li><%= link_to "NEW POST", posts_path, class: 'nav-link' %></li>
            <li><%= link_to "ユーザーのSKATEANDSENTO", posts_path, class: 'nav-link' %></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, data:{ confirm: 'ログアウトしますか？'}, class: 'nav-link'%></li>
            <li><%= link_to "マイページ", my_page_users_path, class: 'nav-link' %></li>
            <li>HELLO!!<%= current_user.name %>!</li>
          </ul>
        <% else %>
          <ul class="nav-list-position">
            <li><%= link_to "新規登録", new_user_registration_path, class: 'nav-link' %></li>
            <li><%= link_to "ログイン", new_user_session_path, class: 'nav-link' %></li>
            <li><%= link_to "ABOUT", about_path, class: 'nav-link' %></li>
            <li><%= link_to "SKATEPARK", parks_path, class: 'nav-link' %></li>
            <li><%= link_to "銭湯", sentos_path, class: 'nav-link' %></li>
          </ul>
        <% end %>
      </div>
    <div class="search">
      <%= render 'public/searches/form' %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SkateAndSento</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <header>
        <div class="header-logos">
          <div class="logo-image mt-3">
           <!--<img src="/assets/6ae60c544e7133acd317435138e2ec92.png" alt="">-->
           <%= image_tag asset_path("top.png", alt: "") %>
          </div>
          <% if request.fullpath.include? "admin" %>
            <div class ="main-logo">
             <%= link_to "管理者用SKATE AND SENTO", root_path, class: "admin-main-logo-link" %>
            </div>
          <% else %>
            <div class ="main-logo">
             <%= link_to "SKATE AND SENTO", root_path, class: "main-logo-link" %>
            </div>
          <% end %>
        </div>
        <%= render 'layouts/header' %>
      </header>
      <main>
        <div class="flash-message-bar">
          <%= flash[:notice] %>
          <div id="flash_message">
            <%= render 'layouts/flash' %>
          </div>
        </div>
        <span id="back">
          <a href="">
            <%= image_tag asset_path('arrow.png'), data: {"turbolinks"=>false}, class: "arrow" %>
          </a>
        </span>
        <%= yield %>
      </main>
    </div>
  </body>
</html>